BOARD_SIZE = 7
NUM_EPISODES = 4000
SELFPLAY_RATIO = 0.25  # 70% self-play, 30% vs base agents
LEARNING_RATE = 1e-4        # Reduced from 1e-3
SELFPLAY_RATIO_MAX = 0.5 # Maximum self-play ratio (e.g., 50%) for self-play ramp-up
SELFPLAY_RAMPUP_FRACTION = 0.7 # Fraction of total episodes over which self-play ratio ramps up
GRAD_CLIP = 1.0             # Tighter gradient clipping
TAU = 0.005                  # Soft update parameter
HUBER_DELTA = 1.0           # Huber loss parameter
TARGET_HARD_UPDATE_INTERVAL = 500  # steps
MOVE_PENALTY = -0.01
WEIGHT_DECAY = 1e-5 
WIN_EFFICIENCY_BONUS_SCALE = 0.8 # Increased scale for bonus for winning quickly
AXIAL_PROGRESS_BONUS_SCALE = 0.05 # Bonus for moves that advance along player's win axis
EMPTY_CELLS_BONUS_SCALE = 0.02 # Bonus for more empty cells remaining when game ends (minor)